# Generated by Django 3.0.9 on 2020-08-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theatre_name', models.CharField(max_length=250)),
                ('screen_name', models.CharField(max_length=100)),
                ('golden_seats', models.IntegerField()),
                ('silver_seats', models.IntegerField()),
                ('is_mvp', models.BooleanField(default=False)),
                ('screen_photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
            ],
        ),
    ]
