# Generated by Django 3.0.9 on 2020-08-16 15:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theatres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('movie_name', models.CharField(max_length=150)),
                ('golden_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('silver_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('released_date', models.DateField(default=datetime.datetime.now)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=2)),
                ('is_published', models.BooleanField(default=False)),
                ('list_date', models.DateTimeField(default=datetime.datetime.now)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='theatres.Screen')),
            ],
        ),
    ]
