# Generated by Django 3.0.9 on 2020-08-20 10:18

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200820_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='teaser',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
