# Generated by Django 3.0.9 on 2020-08-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200820_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='desc',
            field=models.TextField(default='A very good movie', max_length=10000),
        ),
    ]
