# Generated by Django 3.0.9 on 2020-08-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='show_time',
            field=models.TimeField(choices=[('10AM-1PM', 'Morning'), ('2PM-5PM', 'Afternoon'), ('7PM-10PM', 'Evening'), ('11PM-3AM', 'Night')]),
        ),
    ]
