# Generated by Django 3.0.9 on 2020-08-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200821_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='show_time',
            field=models.CharField(choices=[('10AM-1PM', 'Morning'), ('2PM-5PM', 'Afternoon'), ('7PM-10PM', 'Evening'), ('11PM-3AM', 'Night')], max_length=30),
        ),
    ]
